### ISSUE TITLE
"Your configuration URL or path seems broken, please verify it"

### ISSUE THREAD

**Issue by ardacetinkaya** [monitoror/monitoror#217] opened 2020-03-04 16:55 UTC
I have `core.env` and `ui.config` within very simple contents in same path with monitoror, when I run the app, I got the `Your configuration URL or path seems broken, please verify it ` warning.

`http://localhost:8080?configPath=./config.json`

- I am using macOs
- I run with sudo

Any additional thing?

**Comment by Alex-D** [comment] 2020-03-04 16:58
Hey!

First, the `.env` file must be just `.env` without something before the dot

Then, you need to name your file `config.json` and put it in the same folder than the `monitoror` binary :)

**Comment by ardacetinkaya** [comment] 2020-03-04 17:16
Shame on me  :))))

But I did not get; `"put it in the same folder than the monitoror binary :)"`

Do you mean config.json file in same folder with monitoror?If yes, same.

And by the way, it would be nice to define config file in .env file not from query path.

**Comment by Alex-D** [comment] 2020-03-04 17:26
I need to clarify all the Getting Started section I think ^^'

Yep, you should have both `config.json` and monitoror in the same folder.

Idk why it could not works ^^'

**Comment by ardacetinkaya** [comment] 2020-03-04 17:27
So, I got no luck, cause they are in same folder.

**Comment by Alex-D** [comment] 2020-03-04 17:36
What's inside your `config.json`?

Maybe the shown error is not the right one :/

**Comment by ardacetinkaya** [comment] 2020-03-04 17:43
Same from the Documentation exapmple

```{
  "version": "1.0",
  "columns": 2,
  "tiles": [
    {
      "type": "PING",
      "label": "Localhost",
      "params": { "hostname": "127.0.0.1" }
    },
    {
      "type": "PORT",
      "label": "Dev server",
      "params": { "hostname": "127.0.0.1", "port": 8080 }
    }
  ]
}
```
Also try some other thinks...

```
{
    "version": "1.0",
    "columns": 1, //0
    "tiles": [
        { "type": "EMPTY" }
    ]
}
```

**Comment by Alex-D** [comment] 2020-03-04 17:46
Comments are not supported, in the first one, Idk if it's a copy/paste fail or not, but the first `{` is missing

**Comment by Alex-D** [comment] 2020-03-05 18:52
We cannot reproduce your issue :/

Since we are already improving onboarding with #220 and #222 I will close this one to keep things clean :)

**Closed** 2020-03-05 18:52 UTC
Labels: question
