### ISSUE TITLE
Jenkins timeout/host unreachable

### ISSUE THREAD

**Issue by pzelnip** [monitoror/monitoror#273] opened 2020-03-15 16:20 UTC
I've tried setting up a Jenkins build job.  In .env I have:

```
MO_MONITORABLE_JENKINS_URL="https://jenkins.mycompanywebsite.com"
MO_MONITORABLE_JENKINS_LOGIN="myusername"
MO_MONITORABLE_JENKINS_TOKEN="myPassword"
```
In Jenkins, the job I want to track is at https://jenkins.mycompanywebsite.com/job/Shared/job/theJobIWantToMonitor

That is, the job is in a top-level folder called "Shared" and is called "theJobIWantToMonitor".

In config.json I have:

```json
        {
            "type": "JENKINS-BUILD",
            "params": {
                "job": "Shared/job/theJobIWantToMonitor"
            }
        }
```

In monitoror I see:

```
Shared/job/Merge Up or Down
timeout/host unreachable
```
And yet the same machine I'm running monitoror on I can navigate to https://jenkins.mycompanywebsite.com and log in using the credentials in the .env file.

Any suggestions?

**Comment by pzelnip** [comment] 2020-03-17 23:43
Nope, same issue.

![jenkins](https://user-images.githubusercontent.com/414933/76911616-7d885780-686e-11ea-8c83-b817aba49fc7.jpg)

**Comment by jsdidierlaurent** [comment] 2020-04-09 08:37
If the message is "timeout/host unreachable" it's not a tile configuration problem. Monitoror cannot access jenkins.

Can you try this on the monitoror host ?
```
# Linux / Mac
curl http://{jenkins-base-url}/job/{job-name}/api/json --user {user}:{token}
```
```
# Powershell
$Header = @{"Authorization" = "Basic "+[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("{user}:{token}"))}
Invoke-RestMethod -Method GET -Header $Header -uri "{jenkins-base-url}/job/{job-name}/api/json"
```

**Comment by pzelnip** [comment] 2020-04-09 23:13
Yeah that works, I can curl it directly and get) `{"_class":"com.cloudbees.hudson.plugins.folder.Folder","actions":[{},{},{}, .... more JSON data ...`

But in Monitoror with the config I mentioned I see the same error as before.

**Comment by jsdidierlaurent** [comment] 2020-04-10 13:14
Hum

Your job is: https://jenkins.mycompanywebsite.com/job/Shared/job/Foo%20Bar%20Baz/ ?

If you try this ?

```
        {
            "type": "JENKINS-BUILD",
            "params": {
                "job": "Shared",
                "branch": "Foo%20Bar%20Baz"
            }
        }
```

**Comment by pzelnip** [comment] 2020-04-10 16:43
That URL is correct, and tried that config, and same result "timeout/host unreachable".

**Comment by oviliz** [comment] 2020-04-23 09:18
@pzelnip , my Jenkins jobs are organised in different "views", e.g. `https://jenkins.mysite.com/view/Project/job/theJobIWantToMonitor/`, and simply using the job name works.
Have you tried this?
```
        {
            "type": "JENKINS-BUILD",
            "params": {
                "job": "theJobIWantToMonitor"
            }
        }
```

**Comment by Alex-D** [comment] 2020-05-04 09:45
If someone has the error and can give us a docker image or an access to a Jenkins with the above issue, we will get a closer look to this.

For now, as we can't reproduce that on our side, I closed this.

**Closed by Alex-D** 2020-05-04 09:45 UTC
Labels: question

**Comment by dipakdusane** [comment] 2021-03-11 07:25
Seems like it does not work for [jenkins folders](https://plugins.jenkins.io/cloudbees-folder/).
